### ISSUE TITLE
request (if possible)

### ISSUE THREAD

**Issue by nic034** [jwestfall69/neogeo-diag-bios#38]
Hello

first thanks for this awesome work !
Your port is very impressive !

is there possible to add some new cool features like :
- detecting possible cartridge connector issue with the PIN number for example.
- for AES : display a simple motherboard display with defective chip name in red like midway arcade pcb ?
- detect possible power issue due to lack of amps 
- advanced sound diagnostic and easy, in order to detected if sound issue is related to analogic or numeric root cause. 

this could be great.
Thanks

**Comment by jwestfall69** [comment]
> detecting possible cartridge connector issue with the PIN number for example.

There is are custom prog boards here:

https://github.com/jwestfall69/neogeo-diag-mvs-prog
https://github.com/jwestfall69/neogeo-diag-aes-prog

They make it possible to detect issues between the 68k cpu and the program roms on the cart.  These boards help track down crosshatch issues.  Beyond that what you are asking isn't possible because the 68k cpu isn't whats accessing the data on the carts.  So there is no way to test for it.

> for AES : display a simple motherboard display with defective chip name in red like midway arcade pcb ?

I guess its possible but would be a lot of work and require additional custom roms for the graphics.  The diag bios already tells you which ram chip is bad.  It just a matter of going here:

https://github.com/jwestfall69/neogeo-diag-bios/tree/master/docs/ram_locations

so see where its located.

> detect possible power issue due to lack of amps

Not possible.   68k cpu isnt going to know that type of info.  Plus if there wasn't enough power, the board wouldn't be working enough to run the diag bios, right?

> advanced sound diagnostic and easy, in order to detected if sound issue is related to analogic or numeric root cause.

This is a feature that the 240p test suite can do already.

**Comment by nic034** [comment]
Thanks for custom prof board !
did you have a partner who build it ?

**Comment by ragefan** [comment]
Hi, i can send one pcb to you. I built 5 of them a while ago.

**Comment by nic034** [comment]
Thanks !
You’re on delta island French board right ?
